title = "mevlido / Simone Spampinato"
copyright = "&copy;2021-2022 Me"
baseURL = "https://mevlido-s.github.io/"
languageCode = "en-us"
theme = "hugo-split-gallery"

DefaultContentLanguage = "en"



[params]
  robots = "index, follow"
  favicon = ""
  description = "Photo gallery inspired by Hugo Split Theme"
  images = ["DSCF0348.jpg"]
  # customCss = ['css/custom1.css', 'css/custom2.css']
  # customJs = ['js/custom1.js', 'js/custom2.js']
  customCss = ['css/custom.css']
  # enableDownloadAll = false
  footnote = ""
  includeOriginalImage = false
largeImageSize = "1920x q80"  
  # siteLogo = ""
  # useDefaultColors = true
  # useDefaultFonts = true
  galleryLoop = true
  # galleryCounter = true
  # galleryButtons = ["zoom", "slideShow", "close"]
  # galleryAnimationEffect = "zoom"
  # galleryAnimationDuration = 366
  # galleryTransitionEffect = "fade"
  # galleryTransitionDuration = 366
  # gallerySlideshowSpeed = 3000
  # sharedMediaBundle = "/media"
  showTranslations = false
  map2gpx = "en"
  paginate = 10
  # columns = 2
  # columnsMinItems = 10

  [params.taxonomies]
    [params.taxonomies.locations]
      icon = "location-arrow"
    [params.taxonomies.seasons]
      icon = "calendar"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = -110

      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = -100

      

  
        
      
